spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/club?erverTimezone=CST
    username: club
    password: 123456
  data:
    resources:
      static-locations: classpath:static/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080

upload:
  location:
    os: /www/wwwroot/springboot/images
    os1: /www/wwwroot/springboot



